export const jpy = 'jpy'

export const btc = 'btc'
export const etc = 'etc'
export const fct = 'fct'
export const mona = 'mona'
export const eth = 'eth'
export const lsk = 'lsk'
export const xrp = 'xrp'
export const xem = 'xem'
export const ltc = 'ltc'
export const bch = 'bch'
export const xlm = 'xlm'
export const qtum = 'qtum'
export const bat = 'bat'
export const iost = 'iost'
export const plt = 'plt'
